[profile.default]
# Basic nextest configuration for yyaml
retries = 0
test-threads = "num-cpus"
slow-timeout = { period = "60s", terminate-after = 3 }

[profile.default.junit]
path = "target/nextest/results.xml"